### ISSUE TITLE
[iOS] Add the statusBarBackgroundView to all views using page header

### ISSUE THREAD

**Issue by booranger** [CoolestProjects/ios#113]
See homeViews statusBarBackgroundView for details. 

Can we make this reusable? Make the view in code?
<img width="387" alt="screen shot 2017-05-31 at 08 42 56" src="https://cloud.githubusercontent.com/assets/1611528/26621032/28d99c96-45dd-11e7-9b21-2b82964f63ba.png">

**Comment by NatashaColeiOS4Life** [comment]
Done. :)
