### ISSUE TITLE
Ask location permissions

### ISSUE THREAD

**Issue by vavvolo** [CoolestProjects/ios#47]
- [x] Setup the "Always Use" message in the Info.plist
- [x] Ask and handle permissions

**Comment by oi2in** [comment]
[HomeViewController.swift.zip](https://github.com/CoolestProjects/ios/files/924241/HomeViewController.swift.zip)

replace this file in this directory - ios-master\ 4\ copy/CoolestProjects/CoolestProjects/Home/View/HomeViewController
