### ISSUE TITLE
Implement DeepLink to Speaker screen

### ISSUE THREAD

**Issue by vavvolo** [CoolestProjects/ios#52]
- [ ] Navigate to the speaker screen if the pattern matches /speakers/123

**Comment by sdoran** [comment]
Might not need this one. We dont have as many speakers so this page may change to a Workshop listings page

**Comment by richtoolan** [comment]
@sdoran I had to implement this to test before the fix for the stages screen was merged so we got it for free! Sample deeplink structure here: https://github.com/CoolestProjects/ios/blob/a890599ea6cf43438972495c2960347d527a20ad/CoolestProjects/CoolestProjects/Resources/sampleDeeplinks.txt

**Comment by richtoolan** [comment]
It can be quickly migrated to another screen if needed
