### ISSUE TITLE
Handle deep link on local notification interaction

### ISSUE THREAD

**Issue by vavvolo** [CoolestProjects/ios#55]
This is to handle the tap on a local notification displayed after geofence

- [x] handle AppDelegate callbacks (or use UNUserNotification framework to build the action)
- [x] check if notification payload has supported deep link info and navigate

**Comment by vavvolo** [comment]
@sdoran we need more information on this. at the moment, we just display the notification with the title and the message associated to the beacon but if the message is too long it will be truncated and we don't have a place in the app where to show the full message if the user taps on the notification.

**Comment by richtoolan** [comment]
Nice to have: Link to the stage/workshop that is related to the beacon
