### ISSUE TITLE
Create README

### ISSUE THREAD

**Issue by vavvolo** [CoolestProjects/ios#56]
rbenv and cocoapods

**Comment by oi2in** [comment]
[README.md.zip](https://github.com/CoolestProjects/ios/files/924257/README.md.zip)
replace readme.md in the ios-master folder

**Comment by oi2in** [comment]
replace readme.md in the ios-master folder
[README.md 3.zip](https://github.com/CoolestProjects/ios/files/924272/README.md.3.zip)
