### ISSUE TITLE
[iOS] Update home page info

### ISSUE THREAD

**Issue by sdoran** [CoolestProjects/ios#80]
Update text content and images on home page

**Comment by oi2in** [comment]
i'm on it

**Comment by sdoran** [comment]
We have a new design @oi2in from Geo... I have the text  also so maybe don't work on this just yet!

**Comment by booranger** [comment]
@oi2in Any update on this progress? We are planing to make the top header reusable across all the screens https://github.com/CoolestProjects/ios/issues/94

**Comment by sdoran** [comment]
![sponsorsscreenshot_missinggoldandriot](https://cloud.githubusercontent.com/assets/1044653/26284055/89145462-3e2a-11e7-8080-4e1b84a93e9f.png)

Current screenshot from Android - missing gold sponsors and riot logo
