### ISSUE TITLE
[iOS] Populate Project List

### ISSUE THREAD

**Issue by sdoran** [CoolestProjects/ios#82]
May be able to add kids first or last name

**Comment by booranger** [comment]
Data may change

**Comment by booranger** [comment]
New Projects Url is https://dublin.coolestprojects.org/api/project/summary/2

**Comment by booranger** [comment]
<img width="477" alt="screen shot 2017-05-23 at 19 48 28" src="https://cloud.githubusercontent.com/assets/1611528/26370855/0298fc9e-3ff1-11e7-9744-6a87db9427db.png">
