### ISSUE TITLE
[iOS] Convert side menu to Tab bar 

### ISSUE THREAD

**Issue by booranger** [CoolestProjects/ios#91]

**Comment by NatashaColeiOS4Life** [comment]
Work has started on this. Checkout branch: "convertSideMenuToTabbar". :)

**Comment by vavvolo** [comment]
I'm picking what's left in this refactoring

**Comment by vavvolo** [comment]
I've merged the code because of all the changes in shared files like HomeViewController and Main storyboard, the UI is in a almost decent shape, we can work on it :)
