### ISSUE TITLE
[iOS] Create page header

### ISSUE THREAD

**Issue by booranger** [CoolestProjects/ios#94]
<img width="499" alt="screen shot 2017-05-16 at 19 27 11" src="https://cloud.githubusercontent.com/assets/1611528/26121956/cf024f4e-3a6d-11e7-8a6f-91d86d253e65.png">

Should be reusable between all pages. Home, map, halls.

**Comment by NatashaColeiOS4Life** [comment]
I have started work on this on branch: "createPageHeader".

**Comment by booranger** [comment]
Completed. There's a standard view but also a tableViewCell. At the moment I'm just setting it as the tableViewHeader. 

Created a common.strings file too. 

Merged on master 😬 Feel free to change etc.

**Comment by booranger** [comment]
It would be super cool to make this merge into the top nav bar as you scroll down. Just leaving the logo showing in nav bar.
