### ISSUE TITLE
[iOS] Beacon landing screen

### ISSUE THREAD

**Issue by booranger** [CoolestProjects/ios#96]
Show messages 
Explains beacons

@sdoran do we have a design for this otherwise we will copy the current zeplin style.

**Comment by sdoran** [comment]
No design for this yet. Whatever is easiest add in for the moment. Geo finishes his exams next Thursday so I can work with him then to clean it up.

**Comment by richtoolan** [comment]
On a branch will need to be tested with beacons tomorrow night (Sorry I can't make it tomorrow)
