### ISSUE TITLE
[iOS] HomeView: Link to sponsors

### ISSUE THREAD

**Issue by booranger** [CoolestProjects/ios#97]
The sponsors cell on the home view should link to the Sponsors VC. 

https://zpl.io/Z8IcNL

**Comment by booranger** [comment]
<img width="619" alt="screen shot 2017-05-16 at 19 52 03" src="https://cloud.githubusercontent.com/assets/1611528/26122986/44a45e92-3a71-11e7-9455-d596c203a606.png">

**Comment by richtoolan** [comment]
Started working on this but it will be better to pick up after #91

**Comment by vavvolo** [comment]
@Richard-T I've merged part of #91 into master, should be ok now.

**Comment by richtoolan** [comment]
Done as part of the #96 work
